on:
  push:
    tags:
      - '*'

name: Release

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set version
      id: version
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        extensions: mbstring, zip
        coverage: pcov

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --no-suggest

    - name: Build
      run: php dev-cli app:build --build-version=${{ steps.version.outputs.tag }}

    - name: Build Check
      run: php builds/dev-cli --version

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: builds/dev-cli
        asset_name: dev-cli
        tag: ${{ steps.version.outputs.tag }}
        overwrite: true
