on: ['push', 'pull_request']

name: Test & Verify Build

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        extensions: mbstring, zip
        coverage: pcov

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --no-suggest

    - name: Build
      run: php dev-cli app:build --build-version=dev-${{ github.sha }}

    - name: Build Check
      run: php builds/dev-cli --version

    - uses: actions/upload-artifact@v2
      with:
        name: dev-cli
        path: builds/dev-cli
